#! /bin/bash --


# Description: Given N lines of input, print the 3rd character from
#              each line as a new line of output. It is guaranteed that
#              each of the n lines of input will have a 3rd character.

# Input Format: A text file containing N lines of ASCII characters.

# Output Format: For each line of input, print its 3rd character of a new
#              line for a total of N lines of output.

# Sample Input

#    Hello
#    World
#    how are you

# Sample Output

#    l
#    r
#    w

# The script proper -------------
while IFS= read -r line; do

  echo "$line" | cut -b 3

done
